### ISSUE TITLE
testem in tdd mode doesn't seem to behave

### ISSUE THREAD

**Issue by knownasilya** [tildeio/libkit#4]
![screen shot 2018-02-08 at 9 52 17 am](https://user-images.githubusercontent.com/34726/35979258-ddeb95c2-0cb5-11e8-990f-d3459c45a5cd.png)

```
Testem: Error deserializing message: {request: "getUri"}
deserializeMessage @ testem_connection.js:26
handleMessage @ testem_connection.js:52
postMessage (async)
(anonymous) @ extension_properties.js:52
(anonymous) @ extension_properties.js:57

```

And the source maps don't come through.

**Comment by knownasilya** [comment]
Looks like it was fixed here https://github.com/ember-cli/ember-cli/issues/6723

**Comment by knownasilya** [comment]
The cli needs to be updated here to get that fix.

**Comment by knownasilya** [comment]
Looks like updating the cli to lates, which uses testem 2.0.0 doesn't fix the issue.

**Comment by chancancode** [comment]
@knownasilya I'm not sure if I understand the problem: I tried running `npm run tdd` in a fresh libkit project and I got this:

```
TEST'EM 'SCRIPTS!
Open the URL below in a browser to connect.
http://localhost:65345/

━━━━━━━━━━━━━━┓
      Node    ┃     Chrome      Chrome 66.0
    1/1 ✔     ┃    1/1 ✔          1/1 ✔
              ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✔ 1 tests complete.
[Press ENTER to run tests; q to quit; p to pause]
```

There are no errors here, or in Chrome (when I click on the `http://localhost:65345/` link), as far as I can tell. If you are still having this problem feel free to leave another comment with more details and I'll reopen the issue!
